- kind: Message
  name: WatchEpisodeSession
  fields:
    - name: watchSessionId
      type: string
      index: 1
    - name: watcherId
      type: string
      index: 2
    - name: seasonId
      type: string
      index: 3
    - name: episodeId
      type: string
      index: 4
    - name: watchTimeMs # timestamp of the video
      type: number
      index: 5
    - name: lastUpdatedTimeMs
      type: number
      index: 6
- kind: Message
  name: WatchLaterSeason
  fields:
    - name: watcherId
      type: string
      index: 1
    - name: seasonId
      type: string
      index: 2
    - name: addedTimeMs
      type: number
      index: 3
- kind: SpannerDatabase
  name: PlayActivityDatabase
  tables:
    - kind: MessageTable
      name: WatchEpisodeSession
      storedInColumn: data
      columns:
        - watchSessionId
        - watcherId
        - seasonId
        - episodeId
        - lastUpdatedTimeMs
      primaryKeys:
        - watchSessionId
      indexes:
        - name: WatchedByLastUpdatedTime
          columns:
            - watcherId
            - name: lastUpdatedTimeMs
              desc: true
            - seasonId
            - episodeId
      insert: InsertWatchEpisodeSession
      delete: DeleteWatchEpisodeSession
      get: GetWatchEpisodeSession
      update: UpdateWatchEpisodeSession
    - kind: MessageTable
      name: WatchLaterSeason
      storedInColumn: data
      columns:
        - watcherId
        - seasonId
        - addedTimeMs
      primaryKeys:
        - watcherId
        - seasonId
      indexes:
        - name: WatchLaterSeasonByAddedTime
          columns:
            - watcherId
            - name: addedTimeMs
              desc: true
      insert: InsertWatchLaterSeason
      delete: DeleteWatchLaterSeason
      get: GetWatchLaterSeason
      update: UpdateWatchLaterSeason
  selects:
    - name: ListWatchEpisodeSessions
      table: WatchEpisodeSession
      where:
        op: AND
        exps:
          - op: =
            leftColumn: watcherId
          - op: <
            leftColumn: lastUpdatedTimeMs
      orderBy:
        - column: lastUpdatedTimeMs
          desc: true
      withLimit: true
      getColumns:
        - data
    - name: ListWatchEpisodeSessionsBySeason
      table: WatchEpisodeSession
      where:
        op: AND
        exps:
          - op: =
            leftColumn: watcherId
          - op: =
            leftColumn: seasonId
          - op: <
            leftColumn: lastUpdatedTimeMs
      orderBy:
        - column: lastUpdatedTimeMs
          desc: true
      withLimit: true
      getColumns:
        - data
    - name: ListWatchEpisodeSessionsByEpisode
      table: WatchEpisodeSession
      where:
        op: AND
        exps:
          - op: =
            leftColumn: watcherId
          - op: =
            leftColumn: seasonId
          - op: =
            leftColumn: episodeId
          - op: <
            leftColumn: lastUpdatedTimeMs
      orderBy:
        - column: lastUpdatedTimeMs
          desc: true
      withLimit: true
      getColumns:
        - data
    - name: ListWatchLaterSeasons
      table: WatchLaterSeason
      where:
        op: AND
        exps:
          - op: =
            leftColumn: watcherId
          - op: <
            leftColumn: addedTimeMs
      orderBy:
        - column: addedTimeMs
          desc: true
      withLimit: true
      getColumns:
        - data
  outputDdl: ./db/ddl
  outputSql: ./db/sql
