- kind: SpannerDatabase
  name: PlayActivityDatabase
  tables:
    - kind: Table
      name: WatchSession # Watch time is stored in BigTable.
      columns:
        - name: watcherId
          type: string
        - name: watchSessionId
          type: string
        - name: seasonId
          type: string
          nullable: true
        - name: episodeId
          type: string
          nullable: true
        - name: createdTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - watcherId
        - watchSessionId
      indexes:
        - name: WatchSessionByCreatedTime
          columns:
            - watcherId
            - name: createdTimeMs
              desc: true
      insert: InsertWatchSession
      delete: DeleteWatchSession
      get: GetWatchSession
    - kind: Table
      name: WatchedSeason
      columns:
        - name: watcherId
          type: string
        - name: seasonId
          type: string
        - name: latestEpisodeId
          type: string
          nullable: true
        - name: latestWatchSessionId
          type: string
          nullable: true
        - name: updatedTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - watcherId
        - seasonId
      indexes:
        - name: WatchedSeasonByUpdatedTime
          columns:
            - watcherId
            - name: updatedTimeMs
              desc: true
      insert: InsertWatchedSeason
      delete: DeleteWatchedSeason
      get: GetWatchedSeason
      update: UpdateWatchedSeason
    - kind: Table
      name: WatchedEpisode
      columns:
        - name: watcherId
          type: string
        - name: seasonId
          type: string
        - name: episodeId
          type: string
        - name: latestWatchSessionId
          type: string
          nullable: true
        - name: updatedTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - watcherId
        - seasonId
        - episodeId
      insert: InsertWatchedEpisode
      delete: DeleteWatchedEpisode
      get: GetWatchedEpisode
      update: UpdateWatchedEpisode
    - kind: Table
      name: WatchLaterSeason
      columns:
        - name: watcherId
          type: string
        - name: seasonId
          type: string
        - name: addedTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - watcherId
        - seasonId
      indexes:
        - name: WatchLaterSeasonByAddedTime
          columns:
            - watcherId
            - name: addedTimeMs
              desc: true
      insert: InsertWatchLaterSeason
      delete: DeleteWatchLaterSeason
      get: GetWatchLaterSeason
      update: UpdateWatchLaterSeason
  selects:
    - name: ListWatchSessions
      from: WatchSession
      where:
        op: AND
        exprs:
          - op: =
            lColumn: watcherId
          - op: <
            lColumn: createdTimeMs
      orderBy:
        - column: createdTimeMs
          desc: true
      withLimit: true
      get:
        - all: true
    - name: ListWatchedSeasons
      from: WatchedSeason
      where:
        op: AND
        exprs:
          - op: =
            lColumn: watcherId
          - op: <
            lColumn: updatedTimeMs
      orderBy:
        - column: updatedTimeMs
          desc: true
      withLimit: true
      get:
        - all: true
    - name: ListWatchLaterSeasons
      from: WatchLaterSeason
      where:
        op: AND
        exprs:
          - op: =
            lColumn: watcherId
          - op: <
            lColumn: addedTimeMs
      orderBy:
        - column: addedTimeMs
          desc: true
      withLimit: true
      get:
        - all: true
  outputDdl: ./db/ddl
  outputSql: ./db/sql
