- kind: Message
  name: WatchSession
  fields:
    - name: watcherId
      type: string
      index: 1
    - name: watchSessionId
      type: string
      index: 2
    - name: seasonId
      type: string
      index: 3
    - name: episodeId
      type: string
      index: 4
    - name: createdTimeMs
      type: number
      index: 5
- kind: Message
  name: WatchedSeason
  fields:
    - name: watcherId
      type: string
      index: 1
    - name: seasonId
      type: string
      index: 2
    - name: latestEpisodeId
      type: string
      index: 3
    - name: latestEpisodeIndex
      type: number
      index: 4
    - name: latestWatchSessionId
      type: string
      index: 5
    - name: updatedTimeMs
      type: number
      index: 6
- kind: Message
  name: WatchedEpisode
  fields:
    - name: watcherId
      type: string
      index: 1
    - name: seasonId
      type: string
      index: 2
    - name: episodeId
      type: string
      index: 3
    - name: episodeIndex
      type: number
      index: 4
    - name: latestWatchSessionId
      type: string
      index: 5
    - name: updatedTimeMs
      type: number
      index: 6
- kind: Message
  name: WatchLaterSeason
  fields:
    - name: watcherId
      type: string
      index: 1
    - name: seasonId
      type: string
      index: 2
    - name: addedTimeMs
      type: number
      index: 3
- kind: SpannerDatabase
  name: PlayActivityDatabase
  tables:
    - kind: MessageTable
      name: WatchSession # Watch time is stored in BigTable.
      storedInColumn: data
      columns:
        - watcherId
        - watchSessionId
        - createdTimeMs
      primaryKeys:
        - watcherId
        - watchSessionId
      indexes:
        - name: WatchSessionByCreatedTime
          columns:
            - watcherId
            - name: createdTimeMs
              desc: true
      insert: InsertWatchSession
      delete: DeleteWatchSession
      get: GetWatchSession
      update: UpdateWatchSession
    - kind: MessageTable
      name: WatchedSeason
      storedInColumn: data
      columns:
        - watcherId
        - seasonId
        - updatedTimeMs
      primaryKeys:
        - watcherId
        - seasonId
      indexes:
        - name: WatchedSeasonByUpdatedTime
          columns:
            - watcherId
            - name: updatedTimeMs
              desc: true
      insert: InsertWatchedSeason
      delete: DeleteWatchedSeason
      get: GetWatchedSeason
      update: UpdateWatchedSeason
    - kind: MessageTable
      name: WatchedEpisode
      storedInColumn: data
      columns:
        - watcherId
        - seasonId
        - episodeId
        - updatedTimeMs
      primaryKeys:
        - watcherId
        - seasonId
        - episodeId
      insert: InsertWatchedEpisode
      delete: DeleteWatchedEpisode
      get: GetWatchedEpisode
      update: UpdateWatchedEpisode
    - kind: MessageTable
      name: WatchLaterSeason
      storedInColumn: data
      columns:
        - watcherId
        - seasonId
        - addedTimeMs
      primaryKeys:
        - watcherId
        - seasonId
      indexes:
        - name: WatchLaterSeasonByAddedTime
          columns:
            - watcherId
            - name: addedTimeMs
              desc: true
      insert: InsertWatchLaterSeason
      delete: DeleteWatchLaterSeason
      get: GetWatchLaterSeason
      update: UpdateWatchLaterSeason
  selects:
    - name: ListWatchSessions
      table: WatchSession
      where:
        op: AND
        exps:
          - op: =
            leftColumn: watcherId
          - op: <
            leftColumn: createdTimeMs
      orderBy:
        - column: createdTimeMs
          desc: true
      withLimit: true
      getColumns:
        - data
    - name: ListWatchedSeasons
      table: WatchedSeason
      where:
        op: AND
        exps:
          - op: =
            leftColumn: watcherId
          - op: <
            leftColumn: updatedTimeMs
      orderBy:
        - column: updatedTimeMs
          desc: true
      withLimit: true
      getColumns:
        - data
    - name: ListWatchLaterSeasons
      table: WatchLaterSeason
      where:
        op: AND
        exps:
          - op: =
            leftColumn: watcherId
          - op: <
            leftColumn: addedTimeMs
      orderBy:
        - column: addedTimeMs
          desc: true
      withLimit: true
      getColumns:
        - data
  outputDdl: ./db/ddl
  outputSql: ./db/sql
